from pathlib import Path
from html import escape
import re, shutil

ROOT = Path(__file__).parent
OUT = ROOT / "dist"
BASE = "https://blog.enthernet.com"

if OUT.exists():
    shutil.rmtree(OUT)
OUT.mkdir()

DAYS = {
1:("Topic pending archive verification","AWS Networking Foundations"),2:("IAM Users & Least Privilege","AWS Networking Foundations"),3:("Topic pending archive verification","AWS Networking Foundations"),4:("Security Groups","AWS Networking Foundations"),5:("Topic pending archive verification","AWS Networking Foundations"),6:("Topic pending archive verification","AWS Networking Foundations"),7:("Topic pending archive verification","AWS Networking Foundations"),8:("Topic pending archive verification","AWS Networking Foundations"),9:("Topic pending archive verification","AWS Networking Foundations"),10:("Topic pending archive verification","AWS Networking Foundations"),11:("VPC Endpoints","AWS Networking Foundations"),12:("VPC Peering","AWS Networking Foundations"),13:("AWS Transit Gateway","AWS Networking Foundations"),14:("Topic pending archive verification","AWS Networking Foundations"),15:("Topic pending archive verification","AWS Networking Foundations"),16:("Auto Scaling","AWS Networking Foundations"),17:("Topic pending archive verification","AWS Networking Foundations"),18:("Topic pending archive verification","AWS Networking Foundations"),19:("AWS Config","AWS Networking Foundations"),20:("AWS Systems Manager","AWS Networking Foundations"),21:("AWS CloudFormation","AWS Networking Foundations"),22:("AWS CDK","AWS Networking Foundations"),23:("Terraform Introduction","AWS Networking Foundations"),
24:("Introduction to Ansible","Infrastructure Automation"),25:("First Ansible Playbook","Infrastructure Automation"),26:("Ansible Variables","Infrastructure Automation"),27:("Ansible Inventory","Infrastructure Automation"),28:("Ansible Patterns","Infrastructure Automation"),29:("Ansible Ad-Hoc Commands","Infrastructure Automation"),30:("Ansible Modules","Infrastructure Automation"),31:("Ansible Facts","Infrastructure Automation"),32:("Ansible Roles","Infrastructure Automation"),33:("host_vars, group_vars & register","Infrastructure Automation"),34:("Conditionals in Ansible","Infrastructure Automation"),35:("Jinja2 Templates","Infrastructure Automation"),36:("Ansible Handlers","Infrastructure Automation"),37:("Ansible Loops","Infrastructure Automation"),38:("Blocks, Rescue & Always","Infrastructure Automation"),39:("Ansible Galaxy Collections","Infrastructure Automation"),40:("LAMP Automation Capstone","Infrastructure Automation"),
41:("Linux Filesystem","Linux Administration"),42:("Linux Permissions","Linux Administration"),43:("Users, Groups & sudo","Linux Administration"),44:("Processes & Signals","Linux Administration"),45:("systemd","Linux Administration"),46:("journald","Linux Administration"),47:("Cron vs systemd Timers","Linux Administration"),48:("apt & dnf","Linux Administration"),49:("SSH Deep Dive","Linux Administration"),50:("Bash Scripting Automation","Linux Administration"),51:("Linux Networking Tools","Linux Administration"),52:("Linux Hardening","Linux Administration"),
53:("TCP vs UDP","Networking Deep Dive"),54:("DNS & Cloud Security","Networking Deep Dive"),55:("DHCP","Networking Deep Dive"),56:("HTTP vs HTTPS","Networking Deep Dive"),57:("TLS 1.3 Handshake","Networking Deep Dive"),58:("Nginx Reverse Proxy","Networking Deep Dive"),59:("Load Balancing Concepts","Networking Deep Dive"),60:("Network Troubleshooting Sequence","Networking Deep Dive"),
61:("Why Containers","Docker"),62:("Docker Architecture","Docker"),63:("Docker Images","Docker"),64:("Docker Container Lifecycle","Docker"),65:("Docker Volumes","Docker"),66:("Docker Networks","Docker"),67:("Docker Compose","Docker"),68:("Dockerfiles","Docker"),69:("Container Security","Docker"),70:("Docker Deployment","Docker"),
71:("Kubernetes Architecture","Kubernetes"),72:("Kubernetes Pods","Kubernetes"),73:("Kubernetes ReplicaSets","Kubernetes"),74:("Kubernetes Deployments","Kubernetes"),75:("Kubernetes Services","Kubernetes"),76:("Kubernetes Namespaces","Kubernetes"),77:("Kubernetes ConfigMaps","Kubernetes"),78:("Kubernetes Secrets","Kubernetes"),79:("Kubernetes Persistent Storage","Kubernetes"),80:("Kubernetes Ingress","Kubernetes"),81:("Helm","Kubernetes"),82:("Kubernetes Production Deployment","Kubernetes"),83:("CI/CD Foundations","CI/CD & Observability")
}
UNCERTAIN = {1,3,5,6,7,8,9,10,14,15,17,18}
FUTURE = {84:"GitHub Actions",85:"Pipeline Secrets",86:"Automated Testing & Deploy",87:"Prometheus",88:"Grafana",89:"Centralized Logging",90:"Monitoring Dashboard",91:"Shared Responsibility",92:"IAM Best Practices",93:"Secrets Management",94:"GuardDuty & Security Hub",95:"Incident Response",96:"Infrastructure Hardening",97:"DevSecOps Integration",98:"Production Three-Tier Infrastructure",99:"End-to-End Deploy, Monitoring & Security Review",100:"Showcase + Lessons Learned"}

DETAILS = {
40:("A capstone that combines roles for common setup, Apache, PHP and MySQL into one reproducible LAMP deployment.", "Automation gets interesting when failure handling matters: service conflicts, package failures and handlers must be treated as part of the design, not as surprises."),
52:("Hardening Linux by reducing exposed services, applying a default-deny firewall stance and tightening SSH and privilege boundaries.", "Every listening port needs an owner and a reason. A hardening checklist that ignores service inventory is mostly decoration."),
55:("How DHCP assigns network configuration using the client/server exchange carried over UDP.", "The easy-to-mix-up detail: DHCP servers listen on UDP 67 and clients use UDP 68."),
57:("A practical look at TLS 1.3, certificate-chain validation, SNI and what actually happens before encrypted HTTP begins.", "Certificate validity is not enough; the client must be able to build a trusted chain, including the required intermediate certificates."),
58:("Using Nginx as a reverse proxy between clients and an application service, including forwarding headers and loopback-bound backends.", "X-Forwarded-For only helps if the application knows which proxies are trusted; otherwise a header can be forged by the client."),
60:("A repeatable troubleshooting order for network failures: DNS, route, transport, TLS, proxy, backend and finally system pressure such as disk exhaustion.", "Changing random configuration is not troubleshooting. A fixed sequence prevents one symptom from sending you three layers away from the fault."),
61:("Why containers exist: package the application and its userspace dependencies while isolating processes, networking and mounts on a shared host kernel.", "A container is not a tiny virtual machine. It normally shares the host kernel, which is both the efficiency win and part of the security model."),
62:("The Docker client, daemon, image store, registry and runtime path that turns an image into a running container.", "The CLI is not the container runtime itself; it asks the daemon to perform the lifecycle work."),
63:("How layered Docker images are built, tagged, cached and reused to create containers.", "Layer order affects rebuild speed and image size. Frequently changing files belong later when you want useful build-cache hits."),
64:("The container lifecycle from create and start through stop, restart and removal, with the difference between container state and image state.", "Deleting a container does not delete the image it came from, and deleting the container also should not be confused with deleting durable storage."),
65:("How volumes separate durable application data from the lifecycle of an individual container.", "If important state exists only in the writable container layer, container replacement becomes a data-loss procedure with better branding."),
66:("Container communication through Docker networks, especially user-defined bridge networks and name-based service discovery.", "Container IP addresses are disposable. On a user-defined network, applications should use names or aliases rather than hard-coded container IPs."),
67:("Using Docker Compose to define multi-container applications, shared networks, environment configuration and volumes in one declarative file.", "Compose start order does not mean application readiness. A dependency can be running while the service inside it is still unavailable."),
68:("Building repeatable application images with Dockerfiles, including build context, COPY, RUN, WORKDIR, USER and startup instructions.", "COPY reads from the build context, not arbitrary paths on the host. Build context mistakes are a common reason files appear to 'exist' but cannot be copied."),
69:("Reducing the damage a compromised container can do by running as non-root, making the root filesystem read-only, dropping Linux capabilities and avoiding privileged mode.", "Isolation is not the same thing as trust. If the application is compromised, the runtime should expose as little privilege and writable surface as possible."),
70:("Bringing the Docker phase together into a deployable application workflow, connecting image build, runtime configuration, networking, storage and security decisions.", "A deployment is not complete because `docker run` succeeded. Persistence, restart behavior, logs, health and least privilege determine whether it survives real use."),
71:("Kubernetes architecture: the control plane, API server, scheduler, controllers, etcd and node components that continuously reconcile desired state.", "Kubernetes is reconciliation-driven. You describe desired state and controllers keep working toward it rather than executing a one-time script."),
72:("Pods as Kubernetes' smallest deployable unit, grouping one or more containers that share network and selected storage context.", "Containers in the same Pod share a network namespace, so they communicate over localhost rather than through a Service."),
73:("ReplicaSets and the controller loop that maintains a desired number of matching Pod replicas.", "A selector mismatch between the controller and Pod template can produce ownership problems that look far stranger than the YAML that caused them."),
74:("Deployments as the higher-level controller that manages ReplicaSets and declarative rolling application updates.", "The chain is Deployment → ReplicaSet → Pods. Managing ReplicaSets directly throws away the rollout machinery Deployments are designed to provide."),
75:("Services as stable network endpoints over changing Pod replicas, with label selectors connecting traffic to matching backends.", "A Service can exist perfectly while sending traffic nowhere if its selector matches zero Pods."),
76:("Namespaces as a way to scope namespaced Kubernetes resources and apply deliberate organizational or policy boundaries.", "Namespaces are not a security boundary by themselves. RBAC, NetworkPolicy and admission controls determine what the boundary actually means."),
77:("Externalizing non-sensitive configuration with ConfigMaps and consuming it through environment variables or mounted files.", "Environment-variable values do not update inside an existing process, and ConfigMaps mounted through `subPath` do not receive live file updates."),
78:("Handling sensitive configuration with Kubernetes Secrets while separating storage format from actual protection.", "Base64 encoding is not encryption. RBAC, secret distribution, encryption at rest and workload access still decide how protected the value is."),
79:("PersistentVolume, PersistentVolumeClaim and StorageClass working together so application data can outlive an individual Pod.", "A PVC is a request, not the storage itself. Dynamic provisioning depends on an appropriate StorageClass or a compatible pre-existing PV."),
80:("Ingress as HTTP/HTTPS routing into Services, with an Ingress controller implementing the routing behavior.", "Creating an Ingress object does nothing useful if the cluster has no compatible Ingress controller actually watching it."),
81:("Helm for packaging Kubernetes manifests into configurable, reusable releases.", "A chart is not merely templated YAML; release state and upgrade behavior are why Helm becomes operationally useful."),
82:("A production-style Kubernetes flow combining Namespace, ConfigMap, Secret, Deployment, probes, Service, PVC, Ingress and Helm.", "Readiness decides whether a Pod should receive normal Service traffic; liveness answers a different question: whether the container should be restarted."),
83:("CI/CD foundations: turning source changes into a repeatable path through validation, build and deployment rather than relying on manual release rituals.", "A pipeline should make failure visible and stop bad artifacts early. Automation that only makes mistakes faster has technically succeeded at the wrong objective.")
}

SNIPPETS = {
66:"""docker network create app-net\ndocker run -d --name db --network app-net postgres:17-alpine\ndocker run -d --name app --network app-net -p 8080:8000 myapp:1.0""",
69:"""docker run --rm myapp:1.0 id\ndocker run --read-only myapp:1.0\ndocker run --cap-drop=ALL myapp:1.0""",
74:"""kubectl apply -f deployment.yaml\nkubectl get deployments\nkubectl get rs\nkubectl get pods""",
79:"""kubectl get storageclass\nkubectl get pvc\nkubectl get pv""",
82:"""helm upgrade --install myapp ./chart\nkubectl get pods\nkubectl get svc\nkubectl get ingress""",
83:"""source change\n  ↓\nvalidation / tests\n  ↓\nbuild artifact\n  ↓\ndeployment"""
}

CSS = """*{box-sizing:border-box}body{margin:0;background:#07101a;color:#ecf4ff;font:16px/1.65 system-ui,-apple-system,Segoe UI,sans-serif}a{color:inherit;text-decoration:none}.wrap{width:min(1160px,calc(100% - 32px));margin:auto}header{position:sticky;top:0;background:#07101af2;border-bottom:1px solid #203048;z-index:5}nav{min-height:70px;display:flex;align-items:center;gap:20px}.brand{font-weight:900;letter-spacing:.12em;margin-right:auto}.hero{padding:90px 0 60px}.eyebrow,.tag{color:#6ee7ff;text-transform:uppercase;font-size:.75rem;font-weight:850;letter-spacing:.08em}.hero h1,.page h1{font-size:clamp(2.8rem,8vw,6.7rem);line-height:.95;letter-spacing:-.05em;margin:.2em 0}.hero p,.lead{max-width:800px;color:#a9b8cb;font-size:1.15rem}.btn{display:inline-block;padding:12px 17px;border:1px solid #30435f;border-radius:12px;margin:12px 8px 0 0;font-weight:800}.primary{background:#eef6ff;color:#07101a}.external{border-color:#50d8a7}.section{padding:60px 0;border-top:1px solid #142337}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{border:1px solid #203048;background:#0b1623;border-radius:18px;padding:22px}.card h3{margin:.4em 0}.card p,.muted{color:#9fb0c5}.progress{height:11px;background:#17263a;border-radius:99px;overflow:hidden}.progress i{display:block;width:83%;height:100%;background:#6ee7ff}.carousel{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(290px,34%);overflow:auto;gap:16px;padding-bottom:12px}.day{min-height:260px;display:flex;flex-direction:column}.go{margin-top:auto;color:#6ee7ff;font-weight:850}.page{padding:70px 0}.article{max-width:850px}.article h2{margin-top:42px}.notice,.field{border:1px solid #314761;background:#0b1623;padding:18px;border-radius:14px;color:#c4d0df}.field{border-left:4px solid #6ee7ff}.search{width:100%;padding:13px 15px;background:#09131f;border:1px solid #263b56;border-radius:12px;color:white;margin:20px 0}.footer{padding:50px 0;border-top:1px solid #203048;color:#8192a8}pre{overflow:auto;padding:18px;border:1px solid #203048;border-radius:14px;background:#050b12;color:#dcecff}.pill{display:inline-block;padding:4px 9px;border:1px solid #2b415d;border-radius:999px;margin:0 6px 6px 0;color:#a9b8cb;font-size:.85rem}.project-hero{display:grid;grid-template-columns:1.5fr 1fr;gap:20px}.stack{display:flex;flex-wrap:wrap;gap:8px}@media(max-width:800px){nav a:not(.brand){display:none}.grid,.project-hero{grid-template-columns:1fr}.carousel{grid-auto-columns:88%}.hero{padding-top:55px}}"""

JS = """const q=document.querySelector('#q');if(q)q.oninput=()=>{let v=q.value.toLowerCase();document.querySelectorAll('[data-search]').forEach(x=>x.style.display=x.dataset.search.includes(v)?'':'none')}"""

def slug(s):
    return re.sub(r"[^a-z0-9]+","-",s.lower()).strip("-")

def href(d):
    return f"/100-days/day-{d:03d}-{slug(DAYS[d][0])}/"

def layout(title, body, description="Cloud, security, automation and systems engineering documented in public."):
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Enthernet</title><meta name="description" content="{escape(description)}"><link rel="canonical" href="{BASE}"><style>{CSS}</style></head><body><header><nav class="wrap"><a class="brand" href="/">ENTHERNET</a><a href="/100-days/">100 Days</a><a href="/projects/">Projects</a><a href="/articles/">Notes</a><a href="/research/">Research</a><a href="/about/">About</a><a href="/contact/">Contact</a></nav></header>{body}<footer class="footer"><div class="wrap">ENTHERNET · Build it. Verify it. Document the evidence.</div></footer><script>{JS}</script></body></html>"""

def write(path, html):
    p = OUT / path
    if p.suffix:
        p.parent.mkdir(parents=True, exist_ok=True)
    else:
        p.mkdir(parents=True, exist_ok=True)
        p = p / "index.html"
    p.write_text(html, encoding="utf-8")

def generic_detail(title, phase):
    if phase == "AWS Networking Foundations":
        return (f"This day focused on {title} as part of building a practical AWS foundation around identity, networking, scaling and infrastructure control.", "The useful question is not only what the AWS feature does, but which trust or traffic boundary it changes.")
    if phase == "Infrastructure Automation":
        return (f"This day focused on {title} and how Ansible turns host configuration into repeatable, reviewable automation.", "Idempotence matters: a playbook should converge systems toward the desired state rather than blindly repeat side effects.")
    if phase == "Linux Administration":
        return (f"This day focused on {title} as part of operating Linux systems with enough visibility and control to troubleshoot and secure them.", "Administration and security meet at ownership: know which process, user, file and service is responsible before changing it.")
    if phase == "Networking Deep Dive":
        return (f"This day focused on {title} and the network behavior that has to be understood before higher-level cloud or application troubleshooting makes sense.", "Debug from lower layers upward. Application symptoms often begin with DNS, routing or transport failures.")
    return (f"This day focused on {title}.", "The durable record is built around understanding behavior, verifying it and recording the failure modes.")

latest = "".join(
    f'<article class="card day"><span class="tag">Day {d} · {escape(DAYS[d][1])}</span><h3>{escape(DAYS[d][0])}</h3><p>{"Exact topic still requires original archive evidence." if d in UNCERTAIN else DETAILS.get(d,generic_detail(*DAYS[d]))[0]}</p><a class="go" href="{href(d)}">Read Day {d} →</a></article>'
    for d in range(83,73,-1)
)

home = f"""<main><section class="hero"><div class="wrap"><span class="eyebrow">Day 83 / 100 · public engineering journal</span><h1>Cloud. Security. Automation. Evidence.</h1><p>This is the permanent home for my #100DaysOfCloudAndSecurity journey, engineering notes, projects and research. LinkedIn carries the condensed story; this site keeps the durable technical record.</p><a class="btn primary" href="/100-days/">Explore the journey</a><a class="btn" href="https://github.com/Enthernetcode">GitHub ↗</a></div></section>
<section class="section"><div class="wrap"><span class="eyebrow">Progress</span><h2>83 of 100 days</h2><div class="progress"><i></i></div><p class="muted">Current phase: CI/CD & Observability.</p></div></section>
<section class="section"><div class="wrap"><span class="eyebrow">Latest entries</span><h2>One day, one permanent route.</h2><div class="carousel">{latest}</div></div></section>
<section class="section"><div class="wrap"><span class="eyebrow">Live work</span><h2>Projects and research already on the web.</h2><div class="grid">
<article class="card"><h3>Core-Shield Cyber Labs</h3><p>Cybersecurity learning platform built around concept over syntax, browser labs and hands-on practice.</p><a class="go" href="/projects/core-shield/">Project record →</a><br><a class="btn external" href="https://core-shield.enthernetservice.com">Visit live site ↗</a></article>
<article class="card"><h3>Enthernet Pinch AI</h3><p>Research discovery and evidence-tracking assistant built around scholarly sources and auditable metadata.</p><a class="go" href="/projects/pinch-ai/">Project record →</a><br><a class="btn external" href="https://pinchai.enthernetservice.com">Visit live site ↗</a></article>
<article class="card"><h3>Full Cell Sufficiency</h3><p>Research framework exploring resource sufficiency, signalling, wound repair, tissue remodeling and controlled regeneration.</p><a class="go" href="/research/full-cell-sufficiency/">Research record →</a><br><a class="btn external" href="https://fcs.enthernet.com">Visit live site ↗</a></article>
</div></div></section></main>"""
write("index.html", layout("Engineering in Public", home))

cards = "".join(
    f'<article class="card" data-search="day {d} {escape(t.lower())} {escape(p.lower())}"><span class="tag">Day {d} · {escape(p)}</span><h3>{escape(t)}</h3><p>{"Topic verification pending from original artifact evidence." if d in UNCERTAIN else DETAILS.get(d,generic_detail(t,p))[0]}</p><a class="go" href="{href(d)}">Open →</a></article>'
    for d,(t,p) in DAYS.items()
)
future = "".join(f'<article class="card"><span class="tag">Planned · Day {d}</span><h3>{escape(t)}</h3><p>Roadmap entry. Not published yet.</p></article>' for d,t in FUTURE.items())
archive = f"""<main class="page"><div class="wrap"><span class="eyebrow">#100DaysOfCloudAndSecurity</span><h1>83 days. One evidence trail.</h1><p class="lead">Every Day 1–83 route is present. Verified topics now carry topic-specific technical summaries. Twelve early AWS rows remain explicitly unresolved until original artifact evidence closes them.</p><input id="q" class="search" placeholder="Search day, topic or phase"><div class="grid">{cards}</div><section class="section"><h2>Roadmap ahead: Days 84–100</h2><div class="grid">{future}</div></section></div></main>"""
write("100-days", layout("100 Days of Cloud & Security", archive))

for d,(title,phase) in DAYS.items():
    if d in UNCERTAIN:
        record = f"""<div class="notice"><strong>Evidence warning:</strong> this day exists in the published chronology, but the exact topic has not yet been proven by an original post, screenshot, video frame or repository artifact.</div><h2>What closes this gap</h2><p>Recover the original Day {d} artifact. Once verified, this permanent route can be expanded without inventing history.</p>"""
    else:
        summary, field = DETAILS.get(d, generic_detail(title, phase))
        snippet = f"<h2>Hands-on reference</h2><pre>{escape(SNIPPETS[d])}</pre>" if d in SNIPPETS else ""
        record = f"""<p class="lead">{escape(summary)}</p><h2>What this day covered</h2><p>{escape(summary)}</p><div class="field"><strong>Field note:</strong> {escape(field)}</div>{snippet}<h2>Verification mindset</h2><p>The point of the day is not command memorisation. The useful evidence is being able to explain the resource or mechanism, predict its behavior, verify the result and recognize the failure mode when the system disagrees.</p><h2>Archive status</h2><p>This page preserves the verified day/topic mapping and adds a durable technical summary. Original screenshots, repository links and exact published text can be attached as they are recovered without changing this URL.</p>"""
    prev = f'<a class="btn" href="{href(d-1)}">← Day {d-1}</a>' if d > 1 else '<a class="btn" href="/100-days/">← Archive</a>'
    nxt = f'<a class="btn" href="{href(d+1)}">Day {d+1} →</a>' if d < 83 else '<a class="btn" href="/100-days/">Roadmap →</a>'
    body = f"""<main class="page"><div class="wrap article"><span class="eyebrow">Day {d} of 100 · {escape(phase)}</span><h1>{escape(title)}</h1>{record}<p>{prev}{nxt}</p></div></main>"""
    write(href(d).strip("/"), layout(f"Day {d}: {title}", body, f"Day {d} of #100DaysOfCloudAndSecurity: {title}."))

projects = """<main class="page"><div class="wrap"><span class="eyebrow">Projects</span><h1>Systems, not technology bingo cards.</h1><p class="lead">These are working systems with live destinations, architecture decisions and technical lessons behind them.</p><div class="grid">
<article class="card"><h3>Core-Shield Cyber Labs</h3><p>Cybersecurity learning platform with browser labs, AI guidance, certificates and hands-on playground execution.</p><a class="go" href="/projects/core-shield/">Read project record →</a><br><a class="btn external" href="https://core-shield.enthernetservice.com">Live site ↗</a></article>
<article class="card"><h3>Enthernet Pinch AI</h3><p>Research assistant that discovers scholarly sources, normalizes metadata and preserves an audit trail.</p><a class="go" href="/projects/pinch-ai/">Read project record →</a><br><a class="btn external" href="https://pinchai.enthernetservice.com">Live site ↗</a></article>
<article class="card"><h3>JHC Media</h3><p>Live media engine design focused on deterministic clocks, GPU video paths and predictable behavior under load.</p><a class="go" href="/projects/jhc-media/">Read project record →</a></article>
<article class="card"><h3>Automation Systems</h3><p>Mail, task queues, browser automation, infrastructure scripting and operational workflow projects.</p><a class="go" href="/projects/automation-systems/">Read project record →</a></article>
</div></div></main>"""
write("projects", layout("Projects", projects))

core = """<main class="page"><div class="wrap article"><span class="eyebrow">Project · Live</span><h1>Core-Shield Cyber Labs</h1><p class="lead">A cybersecurity learning platform built around the idea that understanding should come before button-clicking: Concept over Syntax. Logic over Code.</p><a class="btn primary external" href="https://core-shield.enthernetservice.com">Open Core-Shield ↗</a><h2>What it contains</h2><p>Dashboard learning flows, course pages, a browser-based playground, an AI mentor and certificate support. The playground has been designed around isolated execution environments for Python, Node.js, Bash and PHP with bounded execution time and output.</p><h2>Learning model</h2><p>The platform is intended to teach how engineers reason about systems, not only which commands to copy. Course areas include Linux for Hackers, reverse proxy concepts, Ansible, web scraping and Wi-Fi security topics.</p><h2>Engineering concerns</h2><p>Running user-supplied code means isolation, resource ceilings, process lifetime, filesystem boundaries and output control are product requirements, not optional hardening.</p></div></main>"""
write("projects/core-shield", layout("Core-Shield Cyber Labs", core))

pinch = """<main class="page"><div class="wrap article"><span class="eyebrow">Project · Live</span><h1>Enthernet Pinch AI</h1><p class="lead">A research discovery and evidence-tracking assistant designed to help researchers find credible scholarly material without losing the provenance behind each result.</p><a class="btn primary external" href="https://pinchai.enthernetservice.com">Open Pinch AI ↗</a><h2>Source integrations</h2><p>OpenAlex, Crossref and Semantic Scholar feed a normalized source model so DOI, journal, author and open-access metadata can be compared rather than trapped in provider-specific responses.</p><h2>Why the audit trail matters</h2><p>A research assistant should not merely produce a citation-shaped sentence. It should preserve enough metadata to show where the source came from and allow the researcher to verify it.</p><h2>Operational details</h2><p>The system accounts for provider rate limits, polite request pools, 429 handling and raw metadata retention alongside normalized fields.</p></div></main>"""
write("projects/pinch-ai", layout("Enthernet Pinch AI", pinch))

jhc = """<main class="page"><div class="wrap article"><span class="eyebrow">Project · Systems engineering</span><h1>JHC Media</h1><p class="lead">A live production engine concept for church media workflows, designed around predictable behavior under load rather than piling features on top of a fragile pipeline.</p><h2>Phase 0 questions</h2><p>What is the master clock? Can a camera frame reach the encoder without leaving the GPU? When encoding falls behind, what gets dropped and who is told?</p><h2>Clock model</h2><p>The current design uses the audio capture clock as master because audible discontinuity is especially punishing in live production.</p><h2>Operator model</h2><p>Preview and Program remain distinct. Bible text, lyrics, announcements and multi-camera inputs are selected without forcing the operator to rebuild layouts during a service.</p></div></main>"""
write("projects/jhc-media", layout("JHC Media", jhc))

automation = """<main class="page"><div class="wrap article"><span class="eyebrow">Project family</span><h1>Automation Systems</h1><p class="lead">A collection of workflow and infrastructure automation projects covering queues, mail protocols, browser automation, scheduling and service operations.</p><h2>Patterns used</h2><p>Python services, Redis-backed queues, Celery workers, IMAP/SMTP integrations, browser automation, Nginx reverse proxying and background job tracking.</p><h2>What matters beyond the happy path</h2><p>Rate limits, retries, idempotence, credential handling, queue visibility, delivery failures and recoverability are the parts that turn an automation script into an operational system.</p></div></main>"""
write("projects/automation-systems", layout("Automation Systems", automation))

notes = """<main class="page"><div class="wrap"><span class="eyebrow">Engineering Notes</span><h1>Details worth remembering because systems enjoy expensive lessons.</h1><div class="grid"><article class="card"><h3>ConfigMap subPath updates</h3><p>Mounted ConfigMap files can update eventually, while subPath mounts do not receive those updates.</p></article><article class="card"><h3>Readiness is traffic eligibility</h3><p>A running Kubernetes Pod can still be excluded from normal Service traffic when readiness fails.</p></article><article class="card"><h3>Docker names beat brittle IPs</h3><p>User-defined bridge networks provide DNS-based service discovery; container IPs can change.</p></article><article class="card"><h3>Every listening port needs an owner</h3><p>Linux hardening starts by making each exposed service justify why it exists.</p></article><article class="card"><h3>DHCP ports</h3><p>Server UDP 67, client UDP 68. Tiny detail, disproportionately popular source of wrong diagrams.</p></article><article class="card"><h3>TLS chain reality</h3><p>A leaf certificate is only useful when clients can build a trusted path through the required intermediates.</p></article></div></div></main>"""
write("articles", layout("Engineering Notes", notes))

research = """<main class="page"><div class="wrap"><span class="eyebrow">Research</span><h1>Separate evidence from the interesting idea.</h1><p class="lead">Research notes are organized so established evidence, supported inference, hypothesis, speculation and open questions do not quietly collapse into one confident paragraph.</p><div class="grid"><article class="card"><h3>Full Cell Sufficiency</h3><p>Wound healing, signalling, mitosis, tissue remodeling, resource sufficiency and controlled regeneration.</p><a class="go" href="/research/full-cell-sufficiency/">Research record →</a><br><a class="btn external" href="https://fcs.enthernet.com">Live research site ↗</a></article></div></div></main>"""
write("research", layout("Research", research))

fcs = """<main class="page"><div class="wrap article"><span class="eyebrow">Research framework · Live</span><h1>Full Cell Sufficiency</h1><p class="lead">An exploratory framework examining whether regeneration and tissue repair can be understood partly through the sufficiency of cellular resources, signals and environmental conditions required for coordinated repair.</p><a class="btn primary external" href="https://fcs.enthernet.com">Open FCS site ↗</a><h2>Research domains</h2><p>Wound healing, cell signalling, mitosis, tissue remodeling, resource sufficiency and controlled regeneration.</p><h2>Evidence discipline</h2><p><span class="pill">Established evidence</span><span class="pill">Supported inference</span><span class="pill">Hypothesis</span><span class="pill">Speculation</span><span class="pill">Open question</span></p><p>The framework should be judged by how clearly those categories stay separated. Interesting mechanisms are not automatically established mechanisms.</p><h2>Current purpose</h2><p>The work is being developed as a research thesis and reading framework, with mechanistic literature used to test where the idea aligns with known biology and where it still requires evidence.</p></div></main>"""
write("research/full-cell-sufficiency", layout("Full Cell Sufficiency", fcs))

about = """<main class="page"><div class="wrap article"><span class="eyebrow">About</span><h1>Build. Break. Understand. Document.</h1><p class="lead">I work across software engineering, cybersecurity, automation, infrastructure, cloud and systems design. This site exists to turn that work into inspectable evidence rather than a list of technologies on a profile.</p><h2>What I am working toward</h2><p>Stronger reasoning across software → infrastructure → cloud → security → automation → systems design, with projects and technical notes showing the path.</p><h2>Why publish the failures too?</h2><p>Because a clean final command does not show whether someone understands the system. Failure modes, corrections and verification usually reveal more.</p></div></main>"""
write("about", layout("About", about))

contact = """<main class="page"><div class="wrap article"><span class="eyebrow">Contact</span><h1>Find the work where it lives.</h1><p class="lead">For engineering, cloud, security, automation or research conversations, use the public project channels below.</p><a class="btn primary" href="https://github.com/Enthernetcode">GitHub ↗</a><a class="btn" href="mailto:enthernet@enthernetservices.com">Email</a><a class="btn" href="https://core-shield.enthernetservice.com">Core-Shield ↗</a><a class="btn" href="https://pinchai.enthernetservice.com">Pinch AI ↗</a><a class="btn" href="https://fcs.enthernet.com">FCS ↗</a></div></main>"""
write("contact", layout("Contact", contact))

write("404.html", layout("Not Found", '<main class="page"><div class="wrap article"><span class="eyebrow">404</span><h1>That route escaped.</h1><p class="lead">The page does not exist or moved before it learned proper change management.</p><a class="btn primary" href="/">Back home</a></div></main>'))
(OUT / "CNAME").write_text("blog.enthernet.com", encoding="utf-8")
(OUT / ".nojekyll").write_text("", encoding="utf-8")
(OUT / "robots.txt").write_text("User-agent: *\nAllow: /\nSitemap: https://blog.enthernet.com/sitemap.xml\n", encoding="utf-8")

urls = ["/","/100-days/","/projects/","/projects/core-shield/","/projects/pinch-ai/","/projects/jhc-media/","/projects/automation-systems/","/articles/","/research/","/research/full-cell-sufficiency/","/about/","/contact/"] + [href(d) for d in DAYS]
sitemap = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + "".join(f"<url><loc>{BASE}{u}</loc></url>" for u in urls) + "</urlset>"
(OUT / "sitemap.xml").write_text(sitemap, encoding="utf-8")
print(f"Generated {len(list(OUT.rglob('*.html')))} HTML pages into {OUT}")
